# Generated by Django 4.0.5 on 2022-07-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_store'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price',)},
        ),
        migrations.AlterModelOptions(
            name='store',
            options={'ordering': ('name',)},
        ),
    ]
