# Generated by Django 4.0.5 on 2022-07-06 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_notificationaboutproduct_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='product',
            name='like',
        ),
        migrations.RemoveField(
            model_name='store',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='store',
            name='like',
        ),
    ]
