# Generated by Django 4.0.5 on 2022-07-07 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_like_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='product',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dislike',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
